#!/usr/bin/env bash
echo "This script helps set up backend (manual steps recommended)."
echo "Backend:"
echo "  cd backend"
echo "  python -m venv .venv"
echo "  source .venv/bin/activate   # Windows PowerShell: .\.venv\\Scripts\\Activate.ps1"
echo "  pip install --upgrade pip"
echo "  pip install -r requirements.txt"
echo "  python db_init.py"
echo "  python sample_data.py"
echo "  python app.py"
echo ""
echo "Frontend:"
echo "  cd frontend"
echo "  npm install"
echo "  npm run dev"
